export const movies = {
  page: 1,
  total_results: 10000,
  total_pages: 500,
  results: [
    {
      popularity: 357.775,
      vote_count: 2002,
      video: false,
      poster_path: "/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
      id: 419704,
      adult: false,
      backdrop_path: "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
      original_language: "en",
      original_title: "Ad Astra",
      genre_ids: [Array],
      title: "Ad Astra",
      vote_average: 6,
      overview:
        "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
      release_date: "2019-09-17"
    },
    {
      popularity: 285.186,
      vote_count: 275,
      video: false,
      poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
      id: 38700,
      adult: false,
      backdrop_path: "/iUspPEAjhUUrLYKntTnKupt3eqV.jpg",
      original_language: "en",
      original_title: "Bad Boys for Life",
      genre_ids: [Array],
      title: "Bad Boys for Life",
      vote_average: 6.7,
      overview:
        "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
      release_date: "2020-01-15"
    },
    {
      popularity: 213.264,
      vote_count: 901,
      video: false,
      poster_path: "/AuGiPiGMYMkSosOJ3BQjDEAiwtO.jpg",
      id: 530915,
      adult: false,
      backdrop_path: "/ds9GKAMhxv5AbprmZ2xCpK8FiEG.jpg",
      original_language: "en",
      original_title: "1917",
      genre_ids: [Array],
      title: "1917",
      vote_average: 8.1,
      overview:
        "At the height of the First World War, two young British soldiers, Schofield and Blake are given a seemingly impossible mission. In a race against time, they must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers—Blake's own brother among them.",
      release_date: "2019-12-10"
    },
    {
      popularity: 183.142,
      vote_count: 8275,
      video: false,
      poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      id: 475557,
      adult: false,
      backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      original_language: "en",
      original_title: "Joker",
      genre_ids: [Array],
      title: "Joker",
      vote_average: 8.3,
      overview:
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      release_date: "2019-10-02"
    },
    {
      popularity: 175.131,
      vote_count: 1118,
      video: false,
      poster_path: "/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg",
      id: 290859,
      adult: false,
      backdrop_path: "/riTANvQ8GKmQbgtC1ps3OfkU43A.jpg",
      original_language: "en",
      original_title: "Terminator: Dark Fate",
      genre_ids: [Array],
      title: "Terminator: Dark Fate",
      vote_average: 6.2,
      overview:
        "Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.",
      release_date: "2019-10-23"
    },
    {
      popularity: 164.452,
      vote_count: 190,
      video: false,
      poster_path: "/yJdeWaVXa2se9agI6B4mQunVYkB.jpg",
      id: 449924,
      adult: false,
      backdrop_path: "/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg",
      original_language: "cn",
      original_title: "葉問4",
      genre_ids: [Array],
      title: "Ip Man 4: The Finale",
      vote_average: 6,
      overview:
        "Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.",
      release_date: "2019-12-20"
    },
    {
      popularity: 113.784,
      vote_count: 2645,
      video: false,
      poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
      id: 181812,
      adult: false,
      backdrop_path: "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
      original_language: "en",
      original_title: "Star Wars: The Rise of Skywalker",
      genre_ids: [Array],
      title: "Star Wars: The Rise of Skywalker",
      vote_average: 6.5,
      overview:
        "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
      release_date: "2019-12-18"
    },
    {
      popularity: 102.505,
      vote_count: 2783,
      video: false,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      id: 496243,
      adult: false,
      backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      original_language: "ko",
      original_title: "기생충",
      genre_ids: [Array],
      title: "Parasite",
      vote_average: 8.6,
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      release_date: "2019-05-30"
    },
    {
      popularity: 98.152,
      vote_count: 1255,
      video: false,
      poster_path: "/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
      id: 512200,
      adult: false,
      backdrop_path: "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
      original_language: "en",
      original_title: "Jumanji: The Next Level",
      genre_ids: [Array],
      title: "Jumanji: The Next Level",
      vote_average: 6.7,
      overview:
        "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
      release_date: "2019-12-04"
    },
    {
      popularity: 91.585,
      vote_count: 57,
      video: false,
      poster_path: "/eU0orGizEpOli4wtN8HtfOOJDlA.jpg",
      id: 516700,
      adult: false,
      backdrop_path: "/mlaX4c2M6usnhXHG5sYJcKVXflA.jpg",
      original_language: "en",
      original_title: "Gundala",
      genre_ids: [Array],
      title: "Gundala",
      vote_average: 5.3,
      overview:
        "Sancaka has lived on the streets since his parents left him. Living a hard life, Sancaka survives by thinking about his own safety. When the condition of the city gets worse and injustice rages throughout the country, Sancaka must decide whether he continues to live to look after himself or rise to become their oppressed hero.",
      release_date: "2019-08-29"
    },
    {
      popularity: 90.477,
      vote_count: 1587,
      video: false,
      poster_path: "/vloNTScJ3w7jwNwtNGoG8DbTThv.jpg",
      id: 420809,
      adult: false,
      backdrop_path: "/skvI4rYFrKXS73BJxWGH54Omlvv.jpg",
      original_language: "en",
      original_title: "Maleficent: Mistress of Evil",
      genre_ids: [Array],
      title: "Maleficent: Mistress of Evil",
      vote_average: 7.2,
      overview:
        "Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions by impending nuptials, unexpected allies, and dark new forces at play.",
      release_date: "2019-10-16"
    },
    {
      popularity: 88.981,
      vote_count: 1961,
      video: false,
      poster_path: "/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
      id: 330457,
      adult: false,
      backdrop_path: "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
      original_language: "en",
      original_title: "Frozen II",
      genre_ids: [Array],
      title: "Frozen II",
      vote_average: 7,
      overview:
        "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
      release_date: "2019-11-20"
    },
    {
      popularity: 75.048,
      vote_count: 16526,
      video: false,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      id: 299536,
      adult: false,
      backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
      original_language: "en",
      original_title: "Avengers: Infinity War",
      genre_ids: [Array],
      title: "Avengers: Infinity War",
      vote_average: 8.3,
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      release_date: "2018-04-25"
    },
    {
      popularity: 76.446,
      vote_count: 79,
      video: false,
      poster_path: "/3Nt3v1uzUgfSuVARD1AnI9g9Zl9.jpg",
      id: 448119,
      adult: false,
      backdrop_path: "/lG802rseTZcN9mtLsQPVfApEVzM.jpg",
      original_language: "en",
      original_title: "Dolittle",
      genre_ids: [Array],
      title: "Dolittle",
      vote_average: 6.7,
      overview:
        "After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.",
      release_date: "2020-01-01"
    },
    {
      popularity: 71.87,
      vote_count: 4175,
      video: false,
      poster_path: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
      id: 466272,
      adult: false,
      backdrop_path: "/yB2hTgz9CTVYjlMWPSl3LPx5nWj.jpg",
      original_language: "en",
      original_title: "Once Upon a Time… in Hollywood",
      genre_ids: [Array],
      title: "Once Upon a Time… in Hollywood",
      vote_average: 7.5,
      overview:
        "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
      release_date: "2019-07-25"
    },
    {
      popularity: 84.545,
      vote_count: 2933,
      video: false,
      poster_path: "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
      id: 474350,
      adult: false,
      backdrop_path: "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
      original_language: "en",
      original_title: "It Chapter Two",
      genre_ids: [Array],
      title: "It Chapter Two",
      vote_average: 6.8,
      overview:
        "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
      release_date: "2019-09-04"
    },
    {
      popularity: 72.418,
      vote_count: 666,
      video: false,
      poster_path: "/mSmiB8XjUnR1GSIljuCPGsk0cwX.jpg",
      id: 331482,
      adult: false,
      backdrop_path: "/3uTxPIdVEXxHpsHOHdJC24QebBV.jpg",
      original_language: "en",
      original_title: "Little Women",
      genre_ids: [Array],
      title: "Little Women",
      vote_average: 8,
      overview:
        "Four sisters come of age in America in the aftermath of the Civil War.",
      release_date: "2019-12-25"
    },
    {
      popularity: 77.084,
      vote_count: 731,
      video: false,
      poster_path: "/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
      id: 515001,
      adult: false,
      backdrop_path: "/agoBZfL1q5G79SD0npArSlJn8BH.jpg",
      original_language: "en",
      original_title: "Jojo Rabbit",
      genre_ids: [Array],
      title: "Jojo Rabbit",
      vote_average: 8.1,
      overview:
        "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
      release_date: "2019-10-18"
    },
    {
      popularity: 103.895,
      vote_count: 758,
      video: false,
      poster_path: "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
      id: 501170,
      adult: false,
      backdrop_path: "/sZAXOoOMyCbBskmqR0f4LShxXtw.jpg",
      original_language: "en",
      original_title: "Doctor Sleep",
      genre_ids: [Array],
      title: "Doctor Sleep",
      vote_average: 7.1,
      overview: `Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'." Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.`,
      release_date: "2019-10-30"
    },
    {
      popularity: 65.285,
      vote_count: 216,
      video: false,
      poster_path: "/jjMJy5OxJHpFIaboCklDIYdcfpD.jpg",
      id: 504562,
      adult: false,
      backdrop_path: "/mJoZVYRTtPI6aMPb1UanuXFC1Zw.jpg",
      original_language: "en",
      original_title: "Motherless Brooklyn",
      genre_ids: [Array],
      title: "Motherless Brooklyn",
      vote_average: 7.1,
      overview:
        "Lionel Essrog, a private detective living with Tourette syndrome, ventures to solve the murder of his mentor and best friend — a mystery that carries him from the gin-soaked jazz clubs of Harlem to the slums of Brooklyn to the gilded halls of New York's power brokers.",
      release_date: "2019-10-31"
    }
  ]
};

export const genres = {
    genres: [
      { id: 28, name: "Action" },
      { id: 12, name: "Adventure" },
      { id: 16, name: "Animation" },
      { id: 35, name: "Comedy" },
      { id: 80, name: "Crime" },
      { id: 99, name: "Documentary" },
      { id: 18, name: "Drama" },
      { id: 10751, name: "Family" },
      { id: 14, name: "Fantasy" },
      { id: 36, name: "History" },
      { id: 27, name: "Horror" },
      { id: 10402, name: "Music" },
      { id: 9648, name: "Mystery" },
      { id: 10749, name: "Romance" },
      { id: 878, name: "Science Fiction" },
      { id: 10770, name: "TV Movie" },
      { id: 53, name: "Thriller" },
      { id: 10752, name: "War" },
      { id: 37, name: "Western" }
    ]
  }